
package Vista;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;

import Controlador.CienciasController;
import Controlador.LoginController;
import Controlador.PanelPerfilController;
import Event.MenuEvent;
import Modelo.Alumno;
import Modelo.AlumnoBuilder;
import Modelo.AlumnoDao;
import raven.alerts.MessageAlerts;
import raven.popup.GlassPanePopup;

import java.awt.Font;

import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.UIManager;


/**
 *
 * @author Jose
 */
public class Aplicacion extends javax.swing.JFrame {
    // Variables para controlador login
    private Alumno usuario;
    private AlumnoDao alDao;

    

    
    /**
     * Creates new form Aplicacion
     */
    public Aplicacion(Alumno usuario) {
        this.usuario = usuario;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("AulaVirtual 1.1 - [Inicio]");
        ImageIcon icon = new ImageIcon(getClass().getResource("/Img/aprender-en-linea.png"));
        setIconImage(icon.getImage());
        txtId.setText("" + usuario.getId());
            txtNombre.setText("" + usuario.getNombre());
            txtApellido.setText("" + usuario.getApellido());
            txtUsuario.setText("" + usuario.getUsuario());
            txtClave.setText("" + usuario.getClave());
            txtPais.setText("" + usuario.getPais());
            txtSexo.setText("" + usuario.getSexo());
            txtEstado.setText("" + usuario.getEstado());

        // Iniciar mensaje
       init();
        CienciasController ciencias = new CienciasController(this); 
        PanelPerfilController perfil = new PanelPerfilController(usuario, alDao, this);
        // Iniciar menu
        MenuEvent event = new MenuEvent() {
            @Override
            public void menuSelected(int index) {
                System.out.println("Selected : " + index);
                switch (index) {
                    case 0:
                        Aplicacion.this.materialTabbed1.setSelectedIndex(2);
                        break;
                    case 1:
                        Aplicacion.this.materialTabbed1.setSelectedIndex(3);
                        break;
                    case 4:
                        Aplicacion.this.materialTabbed1.setSelectedIndex(0);
                        break;
                    
                    case 7:
                        Aplicacion.this.materialTabbed1.setSelectedIndex(1);
                        break;
                    case 9:
                        System.exit(0);
                        break;
                }
                
            }
        };
        menu.initMenu(event);
       
    }

    // Llamar controladores
   
    public void init() {
        GlassPanePopup.install(this);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new Componentes.Menu();
        materialTabbed1 = new Componentes.MaterialTabbed();
        jPanel2 = new javax.swing.JPanel();
        btnCienciasNaturales = new Componentes.Button();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnHistoriaCienciasNaturales = new Componentes.Button();
        jLabel16 = new javax.swing.JLabel();
        btnImportanciaCiencias = new Componentes.Button();
        jLabel17 = new javax.swing.JLabel();
        btnRelacionCiencias = new Componentes.Button();
        jLabel18 = new javax.swing.JLabel();
        btnBiologia = new Componentes.Button();
        jLabel19 = new javax.swing.JLabel();
        btnQuimica = new Componentes.Button();
        btnFisica = new Componentes.Button();
        btnGeologia = new Componentes.Button();
        btnAstronomia = new Componentes.Button();
        btnMicrobiologia = new Componentes.Button();
        btnQuimicaOrganica = new Componentes.Button();
        btnVulcanologia = new Componentes.Button();
        btnFisicaCuantica = new Componentes.Button();
        btnMedicina = new Componentes.Button();
        btnTecnologia = new Componentes.Button();
        btnIndustria = new Componentes.Button();
        btnMedioAmbiente = new Componentes.Button();
        btnPausarCienciasNaturales = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        lblCienciasNaturales = new javax.swing.JLabel();
        lblHistoriaCienciasNaturales = new javax.swing.JLabel();
        lblImportanciaCiencias = new javax.swing.JLabel();
        lblRelacionCiencias = new javax.swing.JLabel();
        lblBiologia = new javax.swing.JLabel();
        lblQuimica = new javax.swing.JLabel();
        lblFisica = new javax.swing.JLabel();
        lblGeologia = new javax.swing.JLabel();
        lblAstronomia = new javax.swing.JLabel();
        lblMicrobiologia = new javax.swing.JLabel();
        lblQuimicaOr = new javax.swing.JLabel();
        lblVulcanologia = new javax.swing.JLabel();
        lblFisicaCuan = new javax.swing.JLabel();
        lblMedicina = new javax.swing.JLabel();
        lblTecnologia = new javax.swing.JLabel();
        lblIndustria = new javax.swing.JLabel();
        lblMedioAmbiente = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelRound1 = new Componentes.PanelRound();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtClave = new javax.swing.JPasswordField();
        txtEstado = new javax.swing.JTextField();
        txtPais = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        btnEditarDatos = new Componentes.Button();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnCuestionarioGame = new Componentes.Button();
        btnUnirPareja = new Componentes.Button();
        btnSopaLetraGames = new Componentes.Button();
        btnConcursoGame = new Componentes.Button();
        btnAnagramaGame = new Componentes.Button();
        btnCrucigrama = new Componentes.Button();
        btnSnake = new Componentes.Button();
        btnAhorcado = new Componentes.Button();
        btnRuleta = new Componentes.Button();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        panelGlowingGradient1 = new Componentes.PanelGlowingGradient();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        button1 = new Componentes.Button();
        panelGlowingGradient2 = new Componentes.PanelGlowingGradient();
        jLabel24 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        button2 = new Componentes.Button();
        panelGlowingGradient3 = new Componentes.PanelGlowingGradient();
        jLabel25 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        button3 = new Componentes.Button();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        materialTabbed1.setBackground(new java.awt.Color(30, 30, 30));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCienciasNaturales.setText("Escuchar");
        jPanel2.add(btnCienciasNaturales, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ciencias Naturales indice tematico");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel14.setText("¿Que son las ciencias naturales?");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel15.setText("Historia de las ciencias naturales");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        btnHistoriaCienciasNaturales.setText("Escuchar");
        jPanel2.add(btnHistoriaCienciasNaturales, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel16.setText("Importancia de las ciencias naturales");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        btnImportanciaCiencias.setText("Escuchar");
        jPanel2.add(btnImportanciaCiencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel17.setText("Ciencias naturales y Bioquimica");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        btnRelacionCiencias.setText("Escuchar");
        jPanel2.add(btnRelacionCiencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        jLabel18.setText("Ramas de las ciencias naturales");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        btnBiologia.setText("Biología");
        jPanel2.add(btnBiologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        jLabel19.setText("Aplicaciones de las ciencias naturales");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));

        btnQuimica.setText("Química");
        jPanel2.add(btnQuimica, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        btnFisica.setText("Física");
        jPanel2.add(btnFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        btnGeologia.setText("Geología");
        jPanel2.add(btnGeologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        btnAstronomia.setText("Astronomía");
        jPanel2.add(btnAstronomia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        btnMicrobiologia.setText("Microbiología");
        jPanel2.add(btnMicrobiologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        btnQuimicaOrganica.setText("Química orgánica");
        jPanel2.add(btnQuimicaOrganica, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));

        btnVulcanologia.setText("Vulcanología");
        jPanel2.add(btnVulcanologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, -1, -1));

        btnFisicaCuantica.setText(" Física cuántica");
        jPanel2.add(btnFisicaCuantica, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, -1, -1));

        btnMedicina.setText("Medicina");
        jPanel2.add(btnMedicina, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, -1, -1));

        btnTecnologia.setText("Tecnología");
        jPanel2.add(btnTecnologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, -1));

        btnIndustria.setText("Industria");
        jPanel2.add(btnIndustria, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, -1, -1));

        btnMedioAmbiente.setText("Medio Ambiente");
        jPanel2.add(btnMedioAmbiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, -1, -1));

        btnPausarCienciasNaturales.setText("Pausar");
        jPanel2.add(btnPausarCienciasNaturales, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));

        jButton2.setText("Siguientes concepto");
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/herbario.png"))); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, -1, -1));

        lblCienciasNaturales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/informacion.png"))); // NOI18N
        jPanel2.add(lblCienciasNaturales, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 94, -1, 30));

        lblHistoriaCienciasNaturales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/informacion.png"))); // NOI18N
        jPanel2.add(lblHistoriaCienciasNaturales, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 174, -1, 30));

        lblImportanciaCiencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/informacion.png"))); // NOI18N
        jPanel2.add(lblImportanciaCiencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 254, -1, 30));

        lblRelacionCiencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/informacion.png"))); // NOI18N
        jPanel2.add(lblRelacionCiencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 334, -1, 30));

        lblBiologia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/informacion.png"))); // NOI18N
        jPanel2.add(lblBiologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 84, -1, 30));

        lblQuimica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/informacion.png"))); // NOI18N
        jPanel2.add(lblQuimica, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 134, -1, 30));

        lblFisica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/informacion.png"))); // NOI18N
        jPanel2.add(lblFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 184, -1, 30));

        lblGeologia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/informacion.png"))); // NOI18N
        jPanel2.add(lblGeologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 234, -1, 30));

        lblAstronomia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/informacion.png"))); // NOI18N
        jPanel2.add(lblAstronomia, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, 30));

        lblMicrobiologia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/informacion.png"))); // NOI18N
        jPanel2.add(lblMicrobiologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, 30));

        lblQuimicaOr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/informacion.png"))); // NOI18N
        jPanel2.add(lblQuimicaOr, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, -1, 30));

        lblVulcanologia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/informacion.png"))); // NOI18N
        jPanel2.add(lblVulcanologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, -1, 30));

        lblFisicaCuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/informacion.png"))); // NOI18N
        jPanel2.add(lblFisicaCuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, -1, 30));

        lblMedicina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/informacion.png"))); // NOI18N
        jPanel2.add(lblMedicina, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 94, -1, 30));

        lblTecnologia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/informacion.png"))); // NOI18N
        jPanel2.add(lblTecnologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 144, -1, 30));

        lblIndustria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/informacion.png"))); // NOI18N
        jPanel2.add(lblIndustria, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 194, -1, 30));

        lblMedioAmbiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/informacion.png"))); // NOI18N
        jPanel2.add(lblMedioAmbiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 244, -1, 30));

        materialTabbed1.addTab("CienciasNaturales", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Datos del Alumno");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 17, -1, -1));

        panelRound1.setBackground(new java.awt.Color(51, 142, 214));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Id:");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Apellido:");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Usuario:");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Clave:");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Pais:");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Sexo:");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Estado:");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Datos Generales");

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(30, 30, 30));
        txtId.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setText("1");

        txtNombre.setBackground(new java.awt.Color(30, 30, 30));
        txtNombre.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));

        txtApellido.setBackground(new java.awt.Color(30, 30, 30));
        txtApellido.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(255, 255, 255));

        txtUsuario.setBackground(new java.awt.Color(30, 30, 30));
        txtUsuario.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));

        txtClave.setBackground(new java.awt.Color(30, 30, 30));
        txtClave.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtClave.setForeground(new java.awt.Color(255, 255, 255));

        txtEstado.setBackground(new java.awt.Color(30, 30, 30));
        txtEstado.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtEstado.setForeground(new java.awt.Color(255, 255, 255));

        txtPais.setBackground(new java.awt.Color(30, 30, 30));
        txtPais.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtPais.setForeground(new java.awt.Color(255, 255, 255));

        txtSexo.setBackground(new java.awt.Color(30, 30, 30));
        txtSexo.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtSexo.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClave)
                            .addComponent(txtEstado)
                            .addComponent(txtPais)
                            .addComponent(txtSexo)
                            .addComponent(txtApellido)
                            .addComponent(txtUsuario)
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(53, 53, 53))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 410, 440));

        btnEditarDatos.setForeground(new java.awt.Color(0, 0, 0));
        btnEditarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/editar-perfil.png"))); // NOI18N
        btnEditarDatos.setText("Editar mis datos");
        btnEditarDatos.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnEditarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDatosActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, -1, -1));

        materialTabbed1.addTab("Mi perfil", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Elige uno de los videojuegos y diviertete");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        btnCuestionarioGame.setForeground(new java.awt.Color(0, 0, 0));
        btnCuestionarioGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cuestionario.png"))); // NOI18N
        btnCuestionarioGame.setText("Cuestionario");
        btnCuestionarioGame.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jPanel4.add(btnCuestionarioGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        btnUnirPareja.setForeground(new java.awt.Color(0, 0, 0));
        btnUnirPareja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/trabajo-en-equipo.png"))); // NOI18N
        btnUnirPareja.setText("Une alas parejas");
        btnUnirPareja.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jPanel4.add(btnUnirPareja, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        btnSopaLetraGames.setForeground(new java.awt.Color(0, 0, 0));
        btnSopaLetraGames.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/sopaLetras.png"))); // NOI18N
        btnSopaLetraGames.setText("Sopa de letras");
        btnSopaLetraGames.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jPanel4.add(btnSopaLetraGames, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, 60));

        btnConcursoGame.setForeground(new java.awt.Color(0, 0, 0));
        btnConcursoGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/examen.png"))); // NOI18N
        btnConcursoGame.setText("Concurso de preguntas");
        btnConcursoGame.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jPanel4.add(btnConcursoGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        btnAnagramaGame.setForeground(new java.awt.Color(0, 0, 0));
        btnAnagramaGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/anagrama.png"))); // NOI18N
        btnAnagramaGame.setText("Anagrama");
        btnAnagramaGame.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jPanel4.add(btnAnagramaGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        btnCrucigrama.setForeground(new java.awt.Color(0, 0, 0));
        btnCrucigrama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/crucigrama.png"))); // NOI18N
        btnCrucigrama.setText("Crucigrama");
        btnCrucigrama.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jPanel4.add(btnCrucigrama, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, -1, -1));

        btnSnake.setForeground(new java.awt.Color(0, 0, 0));
        btnSnake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/serpiente.png"))); // NOI18N
        btnSnake.setText("Snake");
        btnSnake.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jPanel4.add(btnSnake, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        btnAhorcado.setForeground(new java.awt.Color(0, 0, 0));
        btnAhorcado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/juego-del-ahorcado.png"))); // NOI18N
        btnAhorcado.setText("Ahorcado");
        btnAhorcado.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jPanel4.add(btnAhorcado, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        btnRuleta.setForeground(new java.awt.Color(0, 0, 0));
        btnRuleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ruleta.png"))); // NOI18N
        btnRuleta.setText("Ruleta");
        btnRuleta.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jPanel4.add(btnRuleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, -1, -1));

        materialTabbed1.addTab("Juegos", jPanel4);

        jPanel1.setBackground(new java.awt.Color(20, 20, 20));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Bienvenido ala biblioteca virtual");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Ciencias Naturales");
        panelGlowingGradient1.add(jLabel23);
        jLabel23.setBounds(50, 30, 140, 19);

        jLabel26.setText("1. El cuerpo humano");
        panelGlowingGradient1.add(jLabel26);
        jLabel26.setBounds(30, 90, 180, 16);

        jLabel27.setText("2. Plantas y Animales");
        panelGlowingGradient1.add(jLabel27);
        jLabel27.setBounds(30, 110, 170, 16);

        jLabel28.setText("3. El medio ambiente");
        panelGlowingGradient1.add(jLabel28);
        jLabel28.setBounds(30, 130, 120, 16);

        jLabel29.setText("Temas previos");
        panelGlowingGradient1.add(jLabel29);
        jLabel29.setBounds(70, 50, 90, 16);

        jLabel30.setText("4. Fenómenos Naturales");
        panelGlowingGradient1.add(jLabel30);
        jLabel30.setBounds(30, 150, 130, 16);

        button1.setBackground(new java.awt.Color(82, 92, 235));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("Catálogos");
        button1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panelGlowingGradient1.add(button1);
        button1.setBounds(60, 210, 100, 43);

        jPanel1.add(panelGlowingGradient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 240, 290));

        panelGlowingGradient2.setGradientColor1(new java.awt.Color(0, 255, 61));
        panelGlowingGradient2.setGradientColor2(new java.awt.Color(131, 0, 255));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Vocales, Letras y Español");
        panelGlowingGradient2.add(jLabel24);
        jLabel24.setBounds(30, 30, 180, 17);

        jLabel31.setText("Temas previos");
        panelGlowingGradient2.add(jLabel31);
        jLabel31.setBounds(80, 50, 90, 16);

        jLabel33.setText("1. Vocales y Consonantes");
        panelGlowingGradient2.add(jLabel33);
        jLabel33.setBounds(30, 90, 140, 16);

        jLabel34.setText("2. Formación de Palabras");
        panelGlowingGradient2.add(jLabel34);
        jLabel34.setBounds(30, 110, 140, 16);

        jLabel35.setText("3. Lectura y Comprensión");
        panelGlowingGradient2.add(jLabel35);
        jLabel35.setBounds(30, 130, 140, 16);

        jLabel36.setText("4. Gramática Básica");
        panelGlowingGradient2.add(jLabel36);
        jLabel36.setBounds(30, 150, 110, 16);

        button2.setBackground(new java.awt.Color(82, 92, 235));
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setText("Catálogos");
        button2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        panelGlowingGradient2.add(button2);
        button2.setBounds(70, 210, 100, 43);

        jPanel1.add(panelGlowingGradient2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 240, 290));

        panelGlowingGradient3.setGradientColor1(new java.awt.Color(255, 255, 0));
        panelGlowingGradient3.setGradientColor2(new java.awt.Color(102, 255, 102));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Matemáticas");
        panelGlowingGradient3.add(jLabel25);
        jLabel25.setBounds(70, 30, 100, 17);

        jLabel32.setText("Temas previos");
        panelGlowingGradient3.add(jLabel32);
        jLabel32.setBounds(80, 50, 90, 16);

        jLabel37.setText("1. Números y Contar");
        panelGlowingGradient3.add(jLabel37);
        jLabel37.setBounds(30, 90, 120, 16);

        jLabel38.setText("2. Operaciones Básicas");
        panelGlowingGradient3.add(jLabel38);
        jLabel38.setBounds(30, 110, 130, 16);

        jLabel39.setText("3. Geometría Básica");
        panelGlowingGradient3.add(jLabel39);
        jLabel39.setBounds(30, 130, 110, 16);

        jLabel40.setText("4. Conceptos de Tiempo y Dinero");
        panelGlowingGradient3.add(jLabel40);
        jLabel40.setBounds(30, 150, 180, 16);

        button3.setBackground(new java.awt.Color(82, 92, 235));
        button3.setForeground(new java.awt.Color(255, 255, 255));
        button3.setText("Catálogos");
        button3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        panelGlowingGradient3.add(button3);
        button3.setBounds(70, 210, 100, 43);

        jPanel1.add(panelGlowingGradient3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 240, 290));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/flecha.png"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jLabel22.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Explora los contenidos y diviertete leyendo los libros que ofrecemos.");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        materialTabbed1.addTab("Libros Electronicos", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(materialTabbed1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(materialTabbed1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDatosActionPerformed
         // Capturar datos modificados
    String nombre = txtNombre.getText();
    String apellido = txtApellido.getText();
    String usuarioText = txtUsuario.getText();
    String clave = txtClave.getText();
    String pais = txtPais.getText();
    String sexo = txtSexo.getText();
    String estado = txtEstado.getText(); // Asegúrate de tener este campo en tu interfaz gráfica
    
      // Crear objeto Alumno con datos modificados usando AlumnoBuilder
    Alumno alumnoModificado = new AlumnoBuilder()
            .setId(usuario.getId())
            .setNombre(nombre)
            .setApellido(apellido)
            .setUsuario(usuarioText)
            .setClave(clave)
            .setPais(pais)
            .setSexo(sexo)
            .setEstado(estado)
            .build();

    // Llamar al método modificar del DAO
    AlumnoDao alumnoDao = new AlumnoDao();
    String resultado = alumnoDao.modificar(alumnoModificado);

    // Mostrar resultado
    if (resultado.equals("modificado")) {
        JOptionPane.showMessageDialog(this, "Datos modificados correctamente.");
    } else if (resultado.equals("existe")) {
        JOptionPane.showMessageDialog(this, "El alumno con esos datos ya existe.");
    } else {
        JOptionPane.showMessageDialog(this, "Error al modificar los datos.");
    }
    
    }//GEN-LAST:event_btnEditarDatosActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        CatalogoCienciasNaturales cata = new CatalogoCienciasNaturales(usuario);
        cata.setVisible(true);
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatRobotoFont.install();
        FlatLaf.registerCustomDefaultsSource("temas");
        UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 14));
        FlatMacDarkLaf.setup();
        Alumno usuario = new Alumno();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Aplicacion(usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Componentes.Button btnAhorcado;
    private Componentes.Button btnAnagramaGame;
    public Componentes.Button btnAstronomia;
    public Componentes.Button btnBiologia;
    public Componentes.Button btnCienciasNaturales;
    private Componentes.Button btnConcursoGame;
    private Componentes.Button btnCrucigrama;
    private Componentes.Button btnCuestionarioGame;
    public Componentes.Button btnEditarDatos;
    public Componentes.Button btnFisica;
    public Componentes.Button btnFisicaCuantica;
    public Componentes.Button btnGeologia;
    public Componentes.Button btnHistoriaCienciasNaturales;
    public Componentes.Button btnImportanciaCiencias;
    public Componentes.Button btnIndustria;
    public Componentes.Button btnMedicina;
    public Componentes.Button btnMedioAmbiente;
    public Componentes.Button btnMicrobiologia;
    public javax.swing.JButton btnPausarCienciasNaturales;
    public Componentes.Button btnQuimica;
    public Componentes.Button btnQuimicaOrganica;
    public Componentes.Button btnRelacionCiencias;
    private Componentes.Button btnRuleta;
    private Componentes.Button btnSnake;
    private Componentes.Button btnSopaLetraGames;
    public Componentes.Button btnTecnologia;
    private Componentes.Button btnUnirPareja;
    public Componentes.Button btnVulcanologia;
    private Componentes.Button button1;
    private Componentes.Button button2;
    private Componentes.Button button3;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JLabel lblAstronomia;
    public javax.swing.JLabel lblBiologia;
    public javax.swing.JLabel lblCienciasNaturales;
    public javax.swing.JLabel lblFisica;
    public javax.swing.JLabel lblFisicaCuan;
    public javax.swing.JLabel lblGeologia;
    public javax.swing.JLabel lblHistoriaCienciasNaturales;
    public javax.swing.JLabel lblImportanciaCiencias;
    public javax.swing.JLabel lblIndustria;
    public javax.swing.JLabel lblMedicina;
    public javax.swing.JLabel lblMedioAmbiente;
    public javax.swing.JLabel lblMicrobiologia;
    public javax.swing.JLabel lblQuimica;
    public javax.swing.JLabel lblQuimicaOr;
    public javax.swing.JLabel lblRelacionCiencias;
    public javax.swing.JLabel lblTecnologia;
    public javax.swing.JLabel lblVulcanologia;
    private Componentes.MaterialTabbed materialTabbed1;
    private Componentes.Menu menu;
    private Componentes.PanelGlowingGradient panelGlowingGradient1;
    private Componentes.PanelGlowingGradient panelGlowingGradient2;
    private Componentes.PanelGlowingGradient panelGlowingGradient3;
    private Componentes.PanelRound panelRound1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtEstado;
    public javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    

}
